piVersion: apps/v1
kind: Deployment
metadata:
  name: angularapp-deployment
  labels:
    app: angular
spec:
  replicas: 5
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular 
    spec:
      containers:
      - name: angular
        image: gazzehamine/frontend:latest
        ports:
        - containerPort: 4200
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  selector:
    app: angular 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 4200
    nodePort: 31110
