apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  selector:
    matchLabels:
      app: springboot-deployment
  replicas: 5
  template:
    metadata:
      labels:
        app: springboot-deployment
    spec:
      containers:
        - name: springboot
          image: gazzehamine/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081        
        
---

apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  ports:
    - protocol: "TCP"
      port: 8081     
      targetPort: 8081
  type: NodePort        
  selector:
    app: springboot-kubernetes
